title: Require('develop')
description: Record for Memory...

# put your disqus here
disqus_shortname:
reading_time: true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo: images/logo.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: https://dolphago.github.io

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  - title: 'About'
    url: '/about'
  - title: 'Tags'
    url: '/tags'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'

# Owner/author information
owner:
  name: DolphaGo
  site: https://dolphago.github.io
  avatar: images/avatar.jpeg
  bio: "Hello, I'm Serverside engineer."
  email: dev.dolphago@gmail.com
  github: DolphaGo

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: 'github'
    url: 'https://github.com/DolphaGo'

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Seoul
locale: ko_KR
future: true
highlighter: rouge
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:title/

# Amount of post to show on home page
paginate: 7

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: ['.htaccess']
exclude:
  [
    'demo/*',
    'lib',
    'config.rb',
    'Capfile',
    'config',
    'Gemfile',
    'Gemfile.lock',
    'README.md',
    'LICENSE',
    'log',
    'Rakefile',
    'Rakefile.rb',
    'tmp',
    'less',
    '*.sublime-project',
    '*.sublime-workspace',
    'test',
    'spec',
    'Gruntfile.js',
    'package.json',
    'node_modules',
  ]
gems: [jekyll-paginate]
theme: neo-hpstr-jekyll-theme
