name: Require('develop')
description: Hello, World!
meta_description: 'Serverside Engineer'

markdown: kramdown
highlighter: rouge
logo: true
paginate: 15
baseurl: ''
domain_name: 'https://dolphago.github.io'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ''
author: 'DolphaGo'

# Disqus config
disqus-shortname: ''
